python3.13 installing in debian

diff --git a/eng/pipelines/build-whl-pipeline.yml b/eng/pipelines/build-whl-pipeline.yml
--- a/eng/pipelines/build-whl-pipeline.yml
+++ b/eng/pipelines/build-whl-pipeline.yml
@@ -537,6 +537,8 @@ jobs:
         dockerImage: 'ubuntu:22.04'
         distroName: 'Ubuntu'
         packageManager: 'apt'
+
+      # Python 3.13 (x86_64 and ARM64) - Built from source for Debian and RHEL (not available via package managers)
       py313_x86_64_debian:
         pythonVersion: '3.13'
         shortPyVer: '313'
@@ -724,12 +726,12 @@ jobs:
                 apt-get install -y python$(pythonVersion) python$(pythonVersion)-dev python$(pythonVersion)-venv python$(pythonVersion)-distutils
                 PYTHON_CMD=python$(pythonVersion)
                 ;;
-              '3.10'|'3.12'|'3.13')
+              '3.10'|'3.12')
                 # These versions may not be available in Debian 12, use python3 and create symlinks
                 echo 'Python $(pythonVersion) may not be available in Debian 12, using available python3'
                 apt-get install -y python3 python3-dev python3-venv
                 # Note: distutils is not available for Python 3.12+
-                if [ '$(pythonVersion)' != '3.12' ] && [ '$(pythonVersion)' != '3.13' ]; then
+                if [ '$(pythonVersion)' != '3.12' ]; then
                   apt-get install -y python3-distutils || echo 'distutils not available for this Python version'
                 fi
                 # Create symlinks to make the desired version available
@@ -738,6 +740,49 @@ jobs:
                 echo 'Detected Python version:' \$ACTUAL_PYTHON
                 ln -sf /usr/bin/python3 /usr/local/bin/python$(pythonVersion)
                 ln -sf /usr/bin/python3 /usr/local/bin/python
+                PYTHON_CMD=/usr/local/bin/python$(pythonVersion)
+                ;;
+              '3.13')
+                # Python 3.13 requires building from source
+                echo 'Python $(pythonVersion) requires building from source'
+                
+                # Install dependencies needed for Python source compilation
+                apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
+                apt-get install -y libreadline-dev libsqlite3-dev wget curl llvm
+                apt-get install -y libncurses5-dev libncursesw5-dev xz-utils tk-dev
+                apt-get install -y libffi-dev liblzma-dev python3-openssl
+                apt-get install -y libgdbm-dev libnss3-dev libedit-dev || echo 'Some optional dependencies not available'
+                
+                # Download Python source
+                cd /tmp
+                PYTHON_URL='https://www.python.org/ftp/python/3.13.1/Python-3.13.1.tgz'
+                echo \"Downloading Python from \$PYTHON_URL\"
+                wget \$PYTHON_URL -O python-$(pythonVersion).tgz
+                tar -xzf python-$(pythonVersion).tgz
+                cd Python-$(pythonVersion)*
+                
+                # Configure and compile Python with optimizations
+                echo 'Configuring Python build'
+                ./configure --prefix=/usr/local --with-ensurepip=install --enable-loadable-sqlite-extensions --enable-optimizations
+                
+                echo 'Compiling Python (this may take several minutes)'
+                make -j\$(nproc)
+                
+                echo 'Installing Python'
+                make altinstall
+                
+                # Create symlinks
+                ln -sf /usr/local/bin/python$(pythonVersion) /usr/local/bin/python$(pythonVersion)
+                ln -sf /usr/local/bin/python$(pythonVersion) /usr/local/bin/python
+                
+                # Verify installation
+                /usr/local/bin/python$(pythonVersion) --version
+                
+                # Clean up
+                cd /
+                rm -rf /tmp/Python-$(pythonVersion)* /tmp/python-$(pythonVersion).tgz
+                
+                echo 'Successfully built and installed Python $(pythonVersion) from source'
                 PYTHON_CMD=/usr/local/bin/python$(pythonVersion)
                 ;;
               *)
