fix

diff --git a/eng/pipelines/pr-validation-pipeline.yml b/eng/pipelines/pr-validation-pipeline.yml
--- a/eng/pipelines/pr-validation-pipeline.yml
+++ b/eng/pipelines/pr-validation-pipeline.yml
@@ -36,14 +36,37 @@ jobs:
     - script: |
         echo "Running main.py on macOS"
         python main.py
-        displayName: 'Run main.py to ensure Python is working'
-
-    - script: |
-        echo "Build successful, running tests now"
-        python -m pytest -v --junitxml=test-results.xml --cov=. --cov-report=xml --capture=tee-sys --cache-clear
-      displayName: 'Run pytest with coverage'
+      displayName: 'Run main.py to ensure Python is working'
       env:
         # Temporarily Use Azure SQL Database connection string for testing purposes since Docker takes too long to install & start in MacOS
         DB_CONNECTION_STRING: $(AZURE_CONNECTION_STRING)
         # DB_CONNECTION_STRING: 'Driver=ODBC Driver 18 for SQL Server;Server=localhost;Database=master;Uid=SA;Pwd=$(DB_PASSWORD);TrustServerCertificate=yes'
+        DB_PASSWORD: $(DB_PASSWORD)
+
+    # - script: |
+    #     echo "Build successful, running tests now"
+    #     python -m pytest -v --junitxml=test-results.xml --cov=. --cov-report=xml --capture=tee-sys --cache-clear
+    #   displayName: 'Run pytest with coverage'
+    #   env:
+    #     # Temporarily Use Azure SQL Database connection string for testing purposes since Docker takes too long to install & start in MacOS
+    #     DB_CONNECTION_STRING: $(AZURE_CONNECTION_STRING)
+    #     # DB_CONNECTION_STRING: 'Driver=ODBC Driver 18 for SQL Server;Server=localhost;Database=master;Uid=SA;Pwd=$(DB_PASSWORD);TrustServerCertificate=yes'
+    #     DB_PASSWORD: $(DB_PASSWORD)
+
+    - script: |
+        if [ ! -f benchmarks/bench_mssql.py ]; then
+          echo "ERROR: bench_mssql.py not found in benchmarks/"
+          exit 1
+        fi
+        echo "bench_mssql.py found. Proceeding..."
+      displayName: 'Check if benchmarks/bench_mssql.py exists'
+
+    - script: |
+        echo "Installing RichBench and running benchmark script"
+        pip install richbench
+        cd benchmarks
+        richbench bench_mssql.py
+      displayName: 'Run RichBench benchmarks'
+      env:
+        DB_CONNECTION_STRING: $(AZURE_CONNECTION_STRING)
         DB_PASSWORD: $(DB_PASSWORD)
